# Generated by Django 2.1 on 2018-09-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
    ]
