# Generated by Django 2.0.8 on 2018-12-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(height_field='height', null=True, upload_to='pictures', width_field='width'),
        ),
    ]
