# Generated by Django 2.1.4 on 2018-12-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_auto_20181218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(height_field='height', null=True, upload_to='pictures/', width_field='width'),
        ),
    ]
