# Generated by Django 2.1 on 2018-09-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_image_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='pictures/%Y/%m/%d/', width_field='width'),
        ),
    ]
