# Generated by Django 2.1 on 2018-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_auto_20180916_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
