# Generated by Django 2.1.4 on 2018-12-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_auto_20181219_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dummy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
