# Generated by Django 2.1.4 on 2018-12-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_image_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dummy',
        ),
    ]
