# Generated by Django 2.1 on 2018-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0004_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(height_field='height', null=True, upload_to='pictures/%Y/%m/%d/', width_field='width'),
        ),
    ]
