# Generated by Django 2.1.1 on 2018-09-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0007_auto_20180922_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='title',
        ),
    ]
