# Generated by Django 2.1.1 on 2018-10-03 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0009_home_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image_gallery',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
