# Generated by Django 2.1.1 on 2018-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0010_auto_20181002_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='portfolio_section',
            field=models.CharField(choices=[('home', 'Home'), ('35mm color', '35mm Color')], default='Home', max_length=100),
        ),
    ]
