# Generated by Django 2.1.1 on 2018-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0012_home_image_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='portfolio_section',
            field=models.CharField(choices=[('home', 'Home'), ('35mm color', '35mm Color')], max_length=100),
        ),
    ]
