# Generated by Django 2.1.1 on 2018-10-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0014_auto_20181006_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image_gallery',
        ),
        migrations.AlterField(
            model_name='image',
            name='portfolio_section',
            field=models.CharField(choices=[('home', 'Home'), ('35mm color', '35mm Color'), ('prof_pic', 'Profile Picture')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
