# Generated by Django 2.1.1 on 2018-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0016_auto_20181006_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='portfolio_section',
            field=models.CharField(choices=[('home', 'Home'), ('35mm color', '35mm Color'), ('35mm bw', '35mm BW'), ('music', 'Music'), ('prof_pic', 'Profile Picture')], max_length=100),
        ),
    ]
