# Generated by Django 2.1.1 on 2018-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0017_auto_20181007_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='portfolio_section',
            field=models.CharField(choices=[('home', 'Home'), ('colorFilm', '35mm Color'), ('bwFilm', '35mm BW'), ('music', 'Music'), ('prof_pic', 'Profile Picture')], max_length=100),
        ),
    ]
