# Generated by Django 2.1.1 on 2018-11-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0018_auto_20181007_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
