# Generated by Django 2.1.1 on 2018-11-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0019_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_text',
            new_name='body',
        ),
    ]
