# Generated by Django 2.1.1 on 2018-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0021_auto_20181109_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
