# Generated by Django 2.1.1 on 2018-11-10 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0022_auto_20181110_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='prof_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PortfolioApp.Image'),
        ),
    ]
