# Generated by Django 2.1.1 on 2018-12-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0023_about_prof_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
